import mysql from "mysql2/promise";
import dotenv from "dotenv";

dotenv.config();

const connection = await mysql.createConnection(process.env.DATABASE_URL);

const courses = [
  // === PROGRAMMING - BEGINNER ===
  {
    slug: "python-fundamentals",
    title: "Python Fundamentals",
    description: "Learn the basics of Python programming from scratch. Variables, loops, functions, and more.",
    icon: "🐍",
    category: "programming",
    difficulty: "beginner",
    language: "python",
    totalLessons: 24,
    estimatedHours: 12,
    isPremium: false,
    displayOrder: 1,
  },
  {
    slug: "javascript-essentials",
    title: "JavaScript Essentials",
    description: "Master JavaScript from scratch. DOM manipulation, events, async programming.",
    icon: "⚡",
    category: "programming",
    difficulty: "beginner",
    language: "javascript",
    totalLessons: 28,
    estimatedHours: 14,
    isPremium: false,
    displayOrder: 2,
  },
  {
    slug: "python-oop",
    title: "Python OOP & Classes",
    description: "Deep dive into object-oriented programming in Python. Classes, inheritance, polymorphism.",
    icon: "🔷",
    category: "programming",
    difficulty: "intermediate",
    language: "python",
    totalLessons: 20,
    estimatedHours: 10,
    isPremium: false,
    displayOrder: 3,
  },
  {
    slug: "javascript-advanced",
    title: "Advanced JavaScript",
    description: "Closures, prototypes, event loops, async/await, and advanced ES6+ features.",
    icon: "🔥",
    category: "programming",
    difficulty: "advanced",
    language: "javascript",
    totalLessons: 25,
    estimatedHours: 18,
    isPremium: true,
    displayOrder: 4,
  },
  {
    slug: "typescript-complete",
    title: "TypeScript Complete Guide",
    description: "From beginner to expert. Types, interfaces, generics, decorators, and advanced patterns.",
    icon: "🔵",
    category: "programming",
    difficulty: "intermediate",
    language: "javascript",
    totalLessons: 30,
    estimatedHours: 20,
    isPremium: true,
    displayOrder: 5,
  },
  {
    slug: "rust-systems",
    title: "Rust Systems Programming",
    description: "Memory safety, ownership, borrowing, and high-performance systems programming in Rust.",
    icon: "🦀",
    category: "programming",
    difficulty: "advanced",
    language: "other",
    totalLessons: 35,
    estimatedHours: 30,
    isPremium: true,
    displayOrder: 6,
  },
  {
    slug: "go-backend",
    title: "Go Backend Development",
    description: "Build fast, concurrent backends with Go. Goroutines, channels, REST APIs.",
    icon: "🐹",
    category: "programming",
    difficulty: "intermediate",
    language: "other",
    totalLessons: 28,
    estimatedHours: 22,
    isPremium: true,
    displayOrder: 7,
  },
  {
    slug: "cpp-fundamentals",
    title: "C++ Fundamentals",
    description: "Learn C++ from the ground up. Pointers, memory management, STL, and object-oriented design.",
    icon: "⚙️",
    category: "programming",
    difficulty: "intermediate",
    language: "other",
    totalLessons: 30,
    estimatedHours: 25,
    isPremium: false,
    displayOrder: 8,
  },
  {
    slug: "java-programming",
    title: "Java Programming",
    description: "Java fundamentals and OOP. Collections, streams, multithreading, and enterprise patterns.",
    icon: "☕",
    category: "programming",
    difficulty: "intermediate",
    language: "other",
    totalLessons: 32,
    estimatedHours: 24,
    isPremium: false,
    displayOrder: 9,
  },
  {
    slug: "kotlin-android",
    title: "Kotlin for Android",
    description: "Build modern Android apps with Kotlin. Jetpack Compose, ViewModels, coroutines.",
    icon: "📱",
    category: "programming",
    difficulty: "intermediate",
    language: "other",
    totalLessons: 26,
    estimatedHours: 20,
    isPremium: true,
    displayOrder: 10,
  },
  // === WEB DEVELOPMENT ===
  {
    slug: "html-css",
    title: "HTML & CSS Mastery",
    description: "Build beautiful responsive websites from scratch. Flexbox, Grid, animations, and modern CSS.",
    icon: "🎨",
    category: "web-development",
    difficulty: "beginner",
    language: "html",
    totalLessons: 18,
    estimatedHours: 10,
    isPremium: false,
    displayOrder: 11,
  },
  {
    slug: "web-development",
    title: "Full-Stack Web Development",
    description: "Build complete web applications end-to-end. From frontend to database.",
    icon: "🌐",
    category: "web-development",
    difficulty: "intermediate",
    language: "javascript",
    totalLessons: 32,
    estimatedHours: 20,
    isPremium: true,
    displayOrder: 12,
  },
  {
    slug: "react-advanced",
    title: "Advanced React",
    description: "Build complex React applications. State management, performance, hooks, and testing.",
    icon: "⚛️",
    category: "web-development",
    difficulty: "advanced",
    language: "javascript",
    totalLessons: 30,
    estimatedHours: 22,
    isPremium: true,
    displayOrder: 13,
  },
  {
    slug: "react-beginner",
    title: "React for Beginners",
    description: "Start your React journey. Components, props, state, hooks, and JSX fundamentals.",
    icon: "🌟",
    category: "web-development",
    difficulty: "beginner",
    language: "javascript",
    totalLessons: 22,
    estimatedHours: 15,
    isPremium: false,
    displayOrder: 14,
  },
  {
    slug: "vuejs-fundamentals",
    title: "Vue.js Fundamentals",
    description: "Learn Vue.js from scratch. Reactivity, components, Vuex, Vue Router.",
    icon: "💚",
    category: "web-development",
    difficulty: "beginner",
    language: "javascript",
    totalLessons: 20,
    estimatedHours: 14,
    isPremium: false,
    displayOrder: 15,
  },
  {
    slug: "nextjs-complete",
    title: "Next.js Complete Course",
    description: "Full-stack React with Next.js. SSR, SSG, API routes, authentication, deployment.",
    icon: "▲",
    category: "web-development",
    difficulty: "advanced",
    language: "javascript",
    totalLessons: 35,
    estimatedHours: 28,
    isPremium: true,
    displayOrder: 16,
  },
  {
    slug: "nodejs-backend",
    title: "Node.js Backend",
    description: "Build REST APIs with Node.js and Express. Authentication, middleware, deployment.",
    icon: "🟢",
    category: "web-development",
    difficulty: "intermediate",
    language: "javascript",
    totalLessons: 26,
    estimatedHours: 18,
    isPremium: true,
    displayOrder: 17,
  },
  {
    slug: "css-animations",
    title: "CSS Animations & Motion",
    description: "Create stunning web animations. Keyframes, transitions, Framer Motion, GSAP.",
    icon: "✨",
    category: "web-development",
    difficulty: "intermediate",
    language: "html",
    totalLessons: 18,
    estimatedHours: 12,
    isPremium: false,
    displayOrder: 18,
  },
  {
    slug: "graphql-apis",
    title: "GraphQL API Design",
    description: "Build and consume GraphQL APIs. Schemas, resolvers, queries, mutations, subscriptions.",
    icon: "🔷",
    category: "web-development",
    difficulty: "advanced",
    language: "javascript",
    totalLessons: 24,
    estimatedHours: 20,
    isPremium: true,
    displayOrder: 19,
  },
  {
    slug: "tailwind-css",
    title: "Tailwind CSS Mastery",
    description: "Utility-first CSS for rapid UI development. Customization, plugins, responsive design.",
    icon: "🌊",
    category: "web-development",
    difficulty: "beginner",
    language: "html",
    totalLessons: 16,
    estimatedHours: 8,
    isPremium: false,
    displayOrder: 20,
  },
  // === DATA SCIENCE ===
  {
    slug: "data-science-python",
    title: "Data Science with Python",
    description: "Analyze data and build ML models. Pandas, NumPy, Matplotlib, Scikit-Learn.",
    icon: "📊",
    category: "data-science",
    difficulty: "intermediate",
    language: "python",
    totalLessons: 26,
    estimatedHours: 18,
    isPremium: true,
    displayOrder: 21,
  },
  {
    slug: "machine-learning-intro",
    title: "Machine Learning Fundamentals",
    description: "Linear regression, classification, clustering, neural networks. Theory and practice.",
    icon: "🤖",
    category: "data-science",
    difficulty: "intermediate",
    language: "python",
    totalLessons: 30,
    estimatedHours: 25,
    isPremium: true,
    displayOrder: 22,
  },
  {
    slug: "deep-learning",
    title: "Deep Learning with TensorFlow",
    description: "Neural networks, CNNs, RNNs, transformers. Build and deploy deep learning models.",
    icon: "🧠",
    category: "data-science",
    difficulty: "advanced",
    language: "python",
    totalLessons: 35,
    estimatedHours: 30,
    isPremium: true,
    displayOrder: 23,
  },
  {
    slug: "nlp-python",
    title: "Natural Language Processing",
    description: "Text processing, sentiment analysis, named entity recognition, transformers, LLMs.",
    icon: "💬",
    category: "data-science",
    difficulty: "advanced",
    language: "python",
    totalLessons: 28,
    estimatedHours: 25,
    isPremium: true,
    displayOrder: 24,
  },
  {
    slug: "data-visualization",
    title: "Data Visualization",
    description: "Create compelling charts and dashboards. Matplotlib, Seaborn, Plotly, Tableau.",
    icon: "📈",
    category: "data-science",
    difficulty: "beginner",
    language: "python",
    totalLessons: 20,
    estimatedHours: 12,
    isPremium: false,
    displayOrder: 25,
  },
  {
    slug: "statistics-ml",
    title: "Statistics for Machine Learning",
    description: "Probability, distributions, hypothesis testing, Bayesian statistics for ML practitioners.",
    icon: "📉",
    category: "data-science",
    difficulty: "intermediate",
    language: "python",
    totalLessons: 24,
    estimatedHours: 20,
    isPremium: true,
    displayOrder: 26,
  },
  {
    slug: "computer-vision",
    title: "Computer Vision",
    description: "Image processing, object detection, face recognition, OpenCV, YOLO, PyTorch.",
    icon: "👁️",
    category: "data-science",
    difficulty: "advanced",
    language: "python",
    totalLessons: 30,
    estimatedHours: 28,
    isPremium: true,
    displayOrder: 27,
  },
  // === DATABASES ===
  {
    slug: "sql-database",
    title: "SQL & Databases",
    description: "Learn database design, SQL queries, joins, transactions, and optimization.",
    icon: "🗄️",
    category: "databases",
    difficulty: "intermediate",
    language: "sql",
    totalLessons: 22,
    estimatedHours: 15,
    isPremium: false,
    displayOrder: 28,
  },
  {
    slug: "sql-advanced",
    title: "Advanced SQL & Query Optimization",
    description: "Window functions, CTEs, stored procedures, indexing strategies, query planning.",
    icon: "⚡",
    category: "databases",
    difficulty: "advanced",
    language: "sql",
    totalLessons: 20,
    estimatedHours: 16,
    isPremium: true,
    displayOrder: 29,
  },
  {
    slug: "mongodb-nosql",
    title: "MongoDB & NoSQL",
    description: "Document databases, aggregation pipelines, indexing, replication, and sharding.",
    icon: "🍃",
    category: "databases",
    difficulty: "intermediate",
    language: "other",
    totalLessons: 22,
    estimatedHours: 14,
    isPremium: false,
    displayOrder: 30,
  },
  {
    slug: "postgresql-advanced",
    title: "PostgreSQL Advanced",
    description: "Advanced PostgreSQL features, full-text search, JSONB, partitioning, performance tuning.",
    icon: "🐘",
    category: "databases",
    difficulty: "advanced",
    language: "sql",
    totalLessons: 24,
    estimatedHours: 18,
    isPremium: true,
    displayOrder: 31,
  },
  {
    slug: "redis-caching",
    title: "Redis & Caching Strategies",
    description: "In-memory data structures, caching patterns, pub/sub, sessions, rate limiting.",
    icon: "🔴",
    category: "databases",
    difficulty: "intermediate",
    language: "other",
    totalLessons: 18,
    estimatedHours: 12,
    isPremium: false,
    displayOrder: 32,
  },
  {
    slug: "database-design",
    title: "Database Design & Modeling",
    description: "ER diagrams, normalization, schema design, relationships, and best practices.",
    icon: "🗺️",
    category: "databases",
    difficulty: "beginner",
    language: "sql",
    totalLessons: 16,
    estimatedHours: 10,
    isPremium: false,
    displayOrder: 33,
  },
  // === ALGORITHMS ===
  {
    slug: "advanced-algorithms",
    title: "Advanced Algorithms",
    description: "Master complex algorithmic problems. Dynamic programming, graph algorithms, advanced techniques.",
    icon: "🧮",
    category: "algorithms",
    difficulty: "advanced",
    language: "python",
    totalLessons: 20,
    estimatedHours: 25,
    isPremium: true,
    displayOrder: 34,
  },
  {
    slug: "data-structures",
    title: "Data Structures",
    description: "Arrays, linked lists, stacks, queues, trees, graphs, hash maps. Master the fundamentals.",
    icon: "🏗️",
    category: "algorithms",
    difficulty: "intermediate",
    language: "python",
    totalLessons: 24,
    estimatedHours: 20,
    isPremium: false,
    displayOrder: 35,
  },
  {
    slug: "leetcode-patterns",
    title: "LeetCode Patterns",
    description: "Crack coding interviews. Two pointers, sliding window, BFS/DFS, backtracking patterns.",
    icon: "💡",
    category: "algorithms",
    difficulty: "intermediate",
    language: "python",
    totalLessons: 30,
    estimatedHours: 24,
    isPremium: true,
    displayOrder: 36,
  },
  {
    slug: "competitive-programming",
    title: "Competitive Programming",
    description: "Advanced problem solving for competitive contests. Number theory, geometry, advanced graphs.",
    icon: "🏆",
    category: "algorithms",
    difficulty: "advanced",
    language: "python",
    totalLessons: 28,
    estimatedHours: 30,
    isPremium: true,
    displayOrder: 37,
  },
  {
    slug: "sorting-searching",
    title: "Sorting & Searching",
    description: "Quicksort, mergesort, heapsort, binary search, and their applications. Time/space complexity.",
    icon: "🔍",
    category: "algorithms",
    difficulty: "beginner",
    language: "python",
    totalLessons: 16,
    estimatedHours: 12,
    isPremium: false,
    displayOrder: 38,
  },
  // === DEVOPS ===
  {
    slug: "devops-docker",
    title: "DevOps & Docker",
    description: "Deploy applications with Docker. Containers, images, Docker Compose, CI/CD.",
    icon: "🐳",
    category: "devops",
    difficulty: "advanced",
    language: "other",
    totalLessons: 24,
    estimatedHours: 20,
    isPremium: true,
    displayOrder: 39,
  },
  {
    slug: "kubernetes",
    title: "Kubernetes in Practice",
    description: "Container orchestration at scale. Pods, services, deployments, Helm, scaling strategies.",
    icon: "☸️",
    category: "devops",
    difficulty: "advanced",
    language: "other",
    totalLessons: 28,
    estimatedHours: 25,
    isPremium: true,
    displayOrder: 40,
  },
  {
    slug: "cicd-pipelines",
    title: "CI/CD Pipelines",
    description: "Build automated deployment pipelines. GitHub Actions, GitLab CI, Jenkins, ArgoCD.",
    icon: "⚙️",
    category: "devops",
    difficulty: "intermediate",
    language: "other",
    totalLessons: 20,
    estimatedHours: 16,
    isPremium: true,
    displayOrder: 41,
  },
  {
    slug: "aws-cloud",
    title: "AWS Cloud Fundamentals",
    description: "EC2, S3, RDS, Lambda, VPC, IAM. Build and deploy scalable cloud infrastructure.",
    icon: "☁️",
    category: "devops",
    difficulty: "intermediate",
    language: "other",
    totalLessons: 30,
    estimatedHours: 24,
    isPremium: true,
    displayOrder: 42,
  },
  {
    slug: "linux-administration",
    title: "Linux Administration",
    description: "Command line mastery, file systems, process management, networking, shell scripting.",
    icon: "🐧",
    category: "devops",
    difficulty: "beginner",
    language: "other",
    totalLessons: 22,
    estimatedHours: 16,
    isPremium: false,
    displayOrder: 43,
  },
  {
    slug: "terraform-iac",
    title: "Terraform & Infrastructure as Code",
    description: "Provision and manage cloud infrastructure with code. AWS, Azure, GCP providers.",
    icon: "🏔️",
    category: "devops",
    difficulty: "advanced",
    language: "other",
    totalLessons: 24,
    estimatedHours: 20,
    isPremium: true,
    displayOrder: 44,
  },
  // === MATHEMATICS ===
  {
    slug: "mathematics-basics",
    title: "Mathematics for Programmers",
    description: "Essential math concepts for coding. Discrete math, logic, sets, functions.",
    icon: "📐",
    category: "mathematics",
    difficulty: "beginner",
    language: "python",
    totalLessons: 20,
    estimatedHours: 16,
    isPremium: false,
    displayOrder: 45,
  },
  {
    slug: "linear-algebra",
    title: "Linear Algebra for ML",
    description: "Vectors, matrices, eigenvalues, SVD. The mathematical foundation of machine learning.",
    icon: "📊",
    category: "mathematics",
    difficulty: "intermediate",
    language: "python",
    totalLessons: 24,
    estimatedHours: 20,
    isPremium: true,
    displayOrder: 46,
  },
  {
    slug: "calculus-ml",
    title: "Calculus for Machine Learning",
    description: "Derivatives, gradients, optimization. How neural networks learn via backpropagation.",
    icon: "∫",
    category: "mathematics",
    difficulty: "intermediate",
    language: "python",
    totalLessons: 20,
    estimatedHours: 18,
    isPremium: true,
    displayOrder: 47,
  },
  {
    slug: "discrete-mathematics",
    title: "Discrete Mathematics",
    description: "Graph theory, combinatorics, number theory, cryptography fundamentals.",
    icon: "🔢",
    category: "mathematics",
    difficulty: "intermediate",
    language: "python",
    totalLessons: 22,
    estimatedHours: 20,
    isPremium: false,
    displayOrder: 48,
  },
  // === AI/ML ===
  {
    slug: "ai-fundamentals",
    title: "AI Fundamentals",
    description: "Introduction to artificial intelligence. Search, planning, knowledge representation.",
    icon: "🤖",
    category: "ai-ml",
    difficulty: "beginner",
    language: "python",
    totalLessons: 20,
    estimatedHours: 15,
    isPremium: false,
    displayOrder: 49,
  },
  {
    slug: "prompt-engineering",
    title: "Prompt Engineering Mastery",
    description: "Craft perfect prompts for LLMs. Chain-of-thought, few-shot, RAG, and advanced techniques.",
    icon: "💡",
    category: "ai-ml",
    difficulty: "beginner",
    language: "python",
    totalLessons: 16,
    estimatedHours: 10,
    isPremium: false,
    displayOrder: 50,
  },
  {
    slug: "llm-applications",
    title: "Building LLM Applications",
    description: "Build production-ready AI apps. LangChain, vector databases, RAG, agents, fine-tuning.",
    icon: "🔮",
    category: "ai-ml",
    difficulty: "advanced",
    language: "python",
    totalLessons: 30,
    estimatedHours: 25,
    isPremium: true,
    displayOrder: 51,
  },
  {
    slug: "reinforcement-learning",
    title: "Reinforcement Learning",
    description: "Q-learning, policy gradients, DQN, PPO. Build agents that learn through interaction.",
    icon: "🎮",
    category: "ai-ml",
    difficulty: "advanced",
    language: "python",
    totalLessons: 28,
    estimatedHours: 28,
    isPremium: true,
    displayOrder: 52,
  },
  {
    slug: "mlops",
    title: "MLOps & Model Deployment",
    description: "Take ML models to production. MLflow, model serving, monitoring, A/B testing.",
    icon: "🚀",
    category: "ai-ml",
    difficulty: "advanced",
    language: "python",
    totalLessons: 26,
    estimatedHours: 22,
    isPremium: true,
    displayOrder: 53,
  },
  // === SECURITY ===
  {
    slug: "cybersecurity-basics",
    title: "Cybersecurity Fundamentals",
    description: "Security principles, threats, cryptography, network security, ethical hacking basics.",
    icon: "🔐",
    category: "other",
    difficulty: "beginner",
    language: "python",
    totalLessons: 22,
    estimatedHours: 16,
    isPremium: false,
    displayOrder: 54,
  },
  {
    slug: "ethical-hacking",
    title: "Ethical Hacking & Penetration Testing",
    description: "Vulnerability assessment, network scanning, exploitation, CTF challenges.",
    icon: "🕵️",
    category: "other",
    difficulty: "advanced",
    language: "python",
    totalLessons: 28,
    estimatedHours: 24,
    isPremium: true,
    displayOrder: 55,
  },
];

const badges = [
  {
    slug: "first-lesson",
    title: "First Steps",
    description: "Complete your first lesson",
    icon: "🎯",
    badgeType: "achievement",
    criteria: JSON.stringify({ type: "completion", count: 1 }),
  },
  {
    slug: "week-streak",
    title: "Week Warrior",
    description: "Maintain a 7-day streak",
    icon: "🔥",
    badgeType: "streak",
    criteria: JSON.stringify({ type: "streak", days: 7 }),
  },
  {
    slug: "month-streak",
    title: "Month Master",
    description: "Maintain a 30-day streak",
    icon: "🌟",
    badgeType: "streak",
    criteria: JSON.stringify({ type: "streak", days: 30 }),
  },
  {
    slug: "course-complete",
    title: "Course Conqueror",
    description: "Complete an entire course",
    icon: "🏆",
    badgeType: "completion",
    criteria: JSON.stringify({ type: "course_completion", count: 1 }),
  },
  {
    slug: "xp-1000",
    title: "XP Collector",
    description: "Earn 1000 XP",
    icon: "💎",
    badgeType: "milestone",
    criteria: JSON.stringify({ type: "xp", amount: 1000 }),
  },
  {
    slug: "speed-learner",
    title: "Speed Learner",
    description: "Complete 5 lessons in one day",
    icon: "⚡",
    badgeType: "achievement",
    criteria: JSON.stringify({ type: "daily_lessons", count: 5 }),
  },
  {
    slug: "multi-course",
    title: "Multi-Course Master",
    description: "Complete 3 different courses",
    icon: "📚",
    badgeType: "completion",
    criteria: JSON.stringify({ type: "course_completion", count: 3 }),
  },
  {
    slug: "perfect-score",
    title: "Perfect Score",
    description: "Get 100% on a quiz",
    icon: "💯",
    badgeType: "achievement",
    criteria: JSON.stringify({ type: "quiz_perfect", count: 1 }),
  },
];

try {
  console.log("Seeding courses...");
  let seeded = 0;
  for (const course of courses) {
    try {
      await connection.execute(
        `INSERT IGNORE INTO courses (slug, title, description, icon, category, difficulty, language, totalLessons, estimatedHours, isPremium, displayOrder) 
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          course.slug,
          course.title,
          course.description,
          course.icon,
          course.category,
          course.difficulty,
          course.language,
          course.totalLessons,
          course.estimatedHours,
          course.isPremium,
          course.displayOrder,
        ]
      );
      seeded++;
    } catch (err) {
      console.log(`Skipping duplicate: ${course.slug}`);
    }
  }
  console.log(`✓ Seeded/verified ${courses.length} courses (${seeded} new)`);

  console.log("Seeding badges...");
  let badgesSeeded = 0;
  for (const badge of badges) {
    try {
      await connection.execute(
        `INSERT IGNORE INTO badges (slug, title, description, icon, badgeType, criteria) 
         VALUES (?, ?, ?, ?, ?, ?)`,
        [badge.slug, badge.title, badge.description, badge.icon, badge.badgeType, badge.criteria]
      );
      badgesSeeded++;
    } catch (err) {
      console.log(`Skipping duplicate badge: ${badge.slug}`);
    }
  }
  console.log(`✓ Seeded/verified ${badges.length} badges (${badgesSeeded} new)`);

  console.log("✓ Database seeding complete!");
} catch (error) {
  console.error("Error seeding database:", error);
  process.exit(1);
} finally {
  await connection.end();
}
